### PR TITLE
Add support to arm64

### PR DESCRIPTION
**Pull request by TomFreudenberg**
Hi Marcel ( @laverdet )

would you like to add that patch so that node-fibers also will work on arm64.

Cheers
Tom

### CODE REVIEW

**Comment by TomFreudenberg** [comment]
Hi Marcel ( @laverdet )

could you be so kind to inform me just about your thoughts about this PR. Will you include it or may I do something in addition to get that work?

I can confirm now running meteor/node apps on ARM64 (linaro cluster and other device) using the patched fibers from our repository. https://github.com/4commerce-technologies-AG/meteor/issues/42

Thanks for a short info
Tom

**Comment by TomFreudenberg** [comment]
@laverdet Marcel - please give me just a short feedback if you are willing to include this PR

Thanks
Tom

**Comment by laverdet** [comment]
It looks fine, I will include it in the next round of maintenance

**Comment by TomFreudenberg** [comment]
Thanks Marcel

**Comment by TomFreudenberg** [comment]
Hi @laverdet Marcel

Do you have a timeline or expectation when next node-fibers will be released where this PR is included?

Thanks for a short note in advance
Tom

**Comment by laverdet** [comment]
Unless there's any critical bugs that come up and I can slip this in with another release, then probably around October when Node cuts v7 and people need new binaries. Because fibers is feature-complete and in maintenance mode, unless there's a compelling reason I try not to cut too many releases because even small changes affect teams using fibers.

**Comment by TomFreudenberg** [comment]
Hi Marcel, thanks for that info. I will have to check what the release date for meteor 1.4 will be but I guess it is before October. So I will provide the our fork of node-fibers until you have done the new release.

**Comment by laverdet** [comment]
Merged in ef67c62190c90437de8b4883cd7aaf40faa45dbd.

**Pull request closed without merging**
