### PR TITLE
fix circular reference causing memory leak

### PR DESCRIPTION
**Pull request by kyriosli**
I have ran into a situation that the callback of the `Fiber` constructor in return references the new fiber instance, which causes a memory leak. This patch modifies the way that fiber instance references the callback, using internal field of v8's native object, instead of persistents on the wrapped c++ object.

### CODE REVIEW

**Comment by laverdet** [comment]
Could you give more details about the memory leak?

**Comment by laverdet** [comment]
I need more information on the bug. I can't accept a patch that fixes an issue I don't understand.

**Comment by kyriosli** [comment]
Yes, thanks for your attention. Here's a gc trace produced by my performance test script. You can checkout `https://github.com/kyriosli/agentk.git` and type 

    node --harmony --trace-gc --trace-gc-verbose index.js load test/performance.js

Then run `node --harmony test/press.js localhost 3001 100` in another shell.

```
[25321]    29018 ms: Scavenge 147.4 (173.5) -> 134.9 (175.5) MB, 15.7 ms [allocation failure].
[25321] Memory allocator,   used: 179684 KB, available: 1319452 KB
[25321] New space,          used:   1793 KB, available:  14590 KB, committed:  32768 KB
[25321] Old pointers,       used: 123450 KB, available:      0 KB, committed: 124849 KB
[25321] Old data space,     used:  11227 KB, available:      0 KB, committed:  12285 KB
[25321] Code space,         used:   1449 KB, available:   1516 KB, committed:   2988 KB
[25321] Map space,          used:    159 KB, available:    911 KB, committed:   1135 KB
[25321] Cell space,         used:      7 KB, available:    113 KB, committed:    128 KB
[25321] PropertyCell space, used:     26 KB, available:     37 KB, committed:     64 KB
[25321] Large object space, used:      0 KB, available: 1318411 KB, committed:      0 KB
[25321] All spaces,         used: 138114 KB, available:  17169 KB, committed: 174218 KB
[25321] External memory reported: 101443 KB
[25321] Total time spent in GC  : 781.9 ms
```

The `Old pointers` field grows gradually while accepting more and more http requests. Then I took a heap snapshot and loaded it into the Chrome's debugger, it shows that my callback to `Fiber` constructor is never released. Here's the code: (see [co.js](https://github.com/kyriosli/agentk/blob/master/src/co.js)) 

```js
exports.promise = function (cb) {
    let finished = false;
    return new Promise(function (resolve, reject) {
        let fiber = Fiber(function () {
            let ret = cb();
            finished = true;
            return ret;
        });

        sched();
        function sched(args) {
            let result;
            try {
                result = fiber.run(args);
            } catch (e) {
                return reject(e);
            }
            onresult(result);
        }

        function onerr(err) {
            let result;
            try {
                result = fiber.throwInto(err);
            } catch (e) {
                return reject(e);
            }
            onresult(result);
        }

        function onresult(result) {
            if (finished) {
                resolve(result);
                return;
            }
            if (result instanceof Promise) {
                result.then(sched, onerr);
            } else {
                process.nextTick(sched, result);
            }
        }
    });
};
```

So I looked into the `fibers`'s code and thought it was the persistent handle that holds the callback function which causes the memory leak:

  1. The callback will be freed if and only if the C++ object wrap is freed and its destructor is called
  2. The C++ object is freed if and only if the fiber object is freed
  3. The fiber object is freed if and only if there is no reference to it

And that's a dead lock when the callback references the fiber object.

So I tried to change the reference type of the callback from `Persistent` handle to `InternalField` of the fiber object, and it solves the problem, cause it changes the first rule above-mentioned

Here's a new gc log, it shows that the `Old pointer` field if freed when a `Mark-Sweep` happens.

```
[25367] Increasing marking speed to 3 due to high promotion rate
[25367]    30078 ms: Mark-sweep 16.2 (62.5) -> 7.7 (62.5) MB, 7.1 ms (+ 11.8 ms in 70 steps since start of marking, biggest step 0.5 ms) [GC interrupt] [GC in old space requested].
[25367] Memory allocator,   used:  63972 KB, available: 1435164 KB
[25367] New space,          used:   1183 KB, available:  15201 KB, committed:  32768 KB
[25367] Old pointers,       used:   3162 KB, available:     17 KB, committed:  19035 KB
[25367] Old data space,     used:   2112 KB, available:      3 KB, committed:   4223 KB
[25367] Code space,         used:   1204 KB, available:   1766 KB, committed:   2988 KB
[25367] Map space,          used:    154 KB, available:    915 KB, committed:   1135 KB
[25367] Cell space,         used:      6 KB, available:    113 KB, committed:    128 KB
[25367] PropertyCell space, used:     26 KB, available:     37 KB, committed:     64 KB
[25367] Large object space, used:      0 KB, available: 1434123 KB, committed:      0 KB
[25367] All spaces,         used:   7850 KB, available:  18054 KB, committed:  60342 KB
[25367] External memory reported:  99352 KB
[25367] Total time spent in GC  : 810.3 ms
```

**Comment by kyriosli** [comment]
I have read your `README` again and thought maybe it is the way to solve the memory leak mentioned in the last paragraphs.

**Pull request closed without merging**
